global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "object-tracker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["object-tracker:8001"]
        labels:
          instance: "conteo-v6"
